apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api 
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/wanxsky/base-api-ts:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://devuser:devpass@db:5432/myapi
            - name: JWT_SECRETKEY
              value: supersecret