apiVersion: apps/v1
kind: Deployment
metadata:
    name: db
spec:
    replicas: 1
    selector:
        matchLabels:
            app: db 
    template:
        metadata:
            labels:
                app: db
        spec:
            containers:
                - name: postgres
                  image: postgres:15-alpine
                  ports:
                    - containerPort: 5432
                  env:
                    - name: POSTGRES_USER
                      value: devuser
                    - name: POSTGRES_PASSWORD
                      value: devpass
                    - name: POSTGRES_DB
                      value: myapi
                  volumeMounts:
                    - mountPath: /var/lib/postgresql/data 
                      name: postgres-storage
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                    claimName: db-pvc
